import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import ShippingBanner from "./components/ShippingBanner/ShippingBanner";
import { CartProvider } from "./components/cart/CartContext"; // Import CartProvider
import CartSidebar from "./components/cart/CartSidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${jetbrainsMono.variable}`}>
        <CartProvider> {/* Wrap content with CartProvider */}
          <ShippingBanner />
          <Navbar />
          {children}
          <CartSidebar />
        </CartProvider>
      </body>
    </html>
  );
}
